#!/usr/bin/env bash
# Manage the manage_my_process process

case "$1" in
    start)
        ./manage_my_process &
        echo "manage_my_process started"
	echo $! > /var/run/my_process.pid
        ;;

    stop)
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;

    restart)
	echo "manage_my_process restarted"
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        ;;

    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
